// Bundles the automation modules into a single userscript.
//
// Farigh's upstream project loads each module from GitHub at runtime through its
// ComponentLoader. That doesn't suit us: the desktop client has to work offline, and
// Ephenia's script pipeline expects one self-contained file per script. So we
// concatenate the classes in dependency order instead, and reuse the repository's
// standard loadEpheniaScript bootstrap.
//
// Usage: node automation/build.mjs

import { readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const here = dirname(fileURLToPath(import.meta.url));
const repoRoot = join(here, '..');

// Dependency order, mirroring upstream's ComponentLoader: a class must be defined
// before any class whose static initializers reference it.
const SOURCES = [
    'lib/Focus/Achievements.js',
    'lib/Focus/Quests.js',
    'lib/Focus/PokerusCure.js',
    'lib/Focus/ShadowPurification.js',
    'lib/Utils/Battle.js',
    'lib/Utils/Gym.js',
    'lib/Utils/LocalStorage.js',
    'lib/Utils/OakItem.js',
    'lib/Utils/Pokeball.js',
    'lib/Utils/Route.js',
    'lib/Instances/BattleCafe.js',
    'lib/Instances/BattleFrontier.js',
    'lib/Instances/Dungeon.js',
    'lib/Instances/Gym.js',
    'lib/Instances/Safari.js',
    'lib/Click.js',
    'lib/Farm.js',
    'lib/Focus.js',
    'lib/Hatchery.js',
    'lib/Items.js',
    'lib/Menu.js',
    'lib/Notifications.js',
    'lib/Shop.js',
    'lib/Trivia.js',
    'lib/Underground.js',
    'lib/Utils.js',
    'lib/ClickStats.js',
    'lib/SaveBackup.js',
    'lib/Bridges.js',
    'lib/EpheniaControls.js',
    'Automation.js',
];

const SCRIPT_NAME = 'pokeclickerautomation';
const VERSION = '1.1.0';

const HEADER = `// ==UserScript==
// @name          [Pokeclicker] Automation
// @namespace     Pokeclicker Scripts
// @author        GARCIN David (Farigh)
// @description   Automates recurring tasks, presented through an in-game Automation module. Bundled from github.com/Farigh/pokeclicker-automation with a Pokeclicker-native interface.
// @copyright     https://github.com/YggdrasziI
// @license       GPL-3.0 License
// @version       ${VERSION}

// @homepageURL   https://github.com/YggdrasziI/Pokeclicker-Scripts/
// @supportURL    https://github.com/YggdrasziI/Pokeclicker-Scripts/issues
// @downloadURL   https://raw.githubusercontent.com/YggdrasziI/Pokeclicker-Scripts/master/${SCRIPT_NAME}.user.js
// @updateURL     https://raw.githubusercontent.com/YggdrasziI/Pokeclicker-Scripts/master/${SCRIPT_NAME}.user.js

// @match         https://www.pokeclicker.com/
// @icon          https://www.google.com/s2/favicons?domain=pokeclicker.com
// @grant         unsafeWindow
// @run-at        document-idle
// ==/UserScript==

// This file is generated by automation/build.mjs -- do not edit it directly.
// Edit the sources under automation/ and rebuild.
`;

// Reuse the loader that every other script in this repository ships with, so the
// desktop script handler treats this bundle exactly like the rest.
async function readLoader() {
    const donor = await readFile(join(repoRoot, 'enhancedautomine.user.js'), 'utf8');
    const start = donor.indexOf('function loadEpheniaScript(');
    if (start === -1) {
        throw new Error('Could not find loadEpheniaScript in enhancedautomine.user.js');
    }
    // Stop before the donor's own registration call
    const end = donor.indexOf('\nif (!App.isUsingClient', start);
    if (end === -1) {
        throw new Error('Could not find the registration block in enhancedautomine.user.js');
    }
    return donor.slice(start, end).trimEnd();
}

const parts = [HEADER];

for (const relative of SOURCES) {
    const contents = await readFile(join(here, relative), 'utf8');
    parts.push(`\n/* ${'='.repeat(72)}\n * ${relative}\n * ${'='.repeat(72)} */\n`);
    parts.push(contents.trimEnd());
    parts.push('\n');
}

parts.push(`\n/* ${'='.repeat(72)}\n * Bootstrap\n * ${'='.repeat(72)} */\n\n`);
parts.push(await readLoader());
parts.push(`

if (!App.isUsingClient || localStorage.getItem('${SCRIPT_NAME}') === 'true') {
    // Both arguments true: no feature and no setting is enabled by default, so the
    // automation never switches on something the player hasn't unlocked yet.
    loadEpheniaScript('${SCRIPT_NAME}', () => Automation.start(true, true));
}
`);

const output = parts.join('');
const target = join(repoRoot, `${SCRIPT_NAME}.user.js`);
await writeFile(target, output, 'utf8');

console.log(`Wrote ${target}`);
console.log(`  ${SOURCES.length} modules, ${(output.length / 1024).toFixed(1)} KiB`);
